const faces=['U','R','F','D','L','B'];
const colors={U:'#f8f8f8',R:'#e53935',F:'#39b54a',D:'#ffd92f',L:'#ff8c2f',B:'#3385ff'};
let state={};let selected='U';let solution=[];let step=-1;let solverReady=false;let initialFacelets='';let playTimer=null;let rotX=-22;let rotY=-35;

function solved(){const s={};faces.forEach(f=>s[f]=Array(9).fill(f));return s}
function render(){const net=document.getElementById('cube-net');net.innerHTML='';[['U',1,0],['L',0,1],['F',1,1],['R',2,1],['B',3,1],['D',1,2]].forEach(([f,col,row])=>{const el=document.createElement('div');el.className='face';el.style.gridColumn=col+1;el.style.gridRow=row+1;el.innerHTML=`<div class="face-title">${f==='F'?'FRONT':f==='U'?'UP':f==='D'?'DOWN':f==='L'?'LEFT':f==='R'?'RIGHT':'BACK'}</div><div class="stickers"></div>`;const grid=el.querySelector('.stickers');state[f].forEach((v,i)=>{const b=document.createElement('button');b.className='sticker'+(i===4?' fixed':'');b.style.background=colors[v];b.title=`${f}${i+1}`;b.disabled=i===4;b.onclick=()=>{state[f][i]=selected;render()};grid.appendChild(b)});net.appendChild(el)});renderPalette()}
function renderPalette(){const p=document.getElementById('palette');p.innerHTML='';faces.forEach(f=>{const b=document.createElement('button');b.className='color-btn'+(selected===f?' selected':'');b.style.background=colors[f];b.title=f;b.onclick=()=>{selected=f;renderPalette()};p.appendChild(b)})}
function reset(){stopPlayback();state=solved();selected='U';solution=[];step=-1;initialFacelets='';document.getElementById('solution-card').classList.add('hidden');document.getElementById('status').textContent='';render()}
function facelets(){return faces.map(f=>state[f].join('')).join('')}
function validate(){const counts=Object.fromEntries(faces.map(f=>[f,0]));for(const f of faces)for(const c of state[f]){if(!(c in counts))return 'Invalid color';counts[c]++}for(const f of faces)if(counts[f]!==9)return `You need exactly 9 ${f} stickers.`;return null}

function build3D(){faces.forEach(f=>{const el=document.querySelector(`.cube3d-${f}`);el.innerHTML='';for(let i=0;i<9;i++){const s=document.createElement('div');s.className='cube-sticker';el.appendChild(s)}});document.getElementById('cube3d').style.transform=`rotateX(${rotX}deg) rotateY(${rotY}deg)`}
function render3D(str,activeMove=''){if(!str)return;for(let fi=0;fi<faces.length;fi++){const f=faces[fi];const el=document.querySelector(`.cube3d-${f}`);const values=str.slice(fi*9,fi*9+9).split('');el.querySelectorAll('.cube-sticker').forEach((s,i)=>s.style.background=colors[values[i]]);el.classList.toggle('active-face',activeMove.startsWith(f))}}
function playbackState(targetStep){let c=Cube.fromString(initialFacelets);if(targetStep>=0&&solution.length)c.move(solution.slice(0,targetStep+1).join(' '));return c.asString()}
function setStep(targetStep){if(targetStep<-1)targetStep=-1;if(targetStep>=solution.length)targetStep=solution.length-1;step=targetStep;const active=step<0?'':solution[step]||'';render3D(playbackState(step),active);document.querySelectorAll('.move').forEach((b,i)=>b.classList.toggle('active',i===step));document.getElementById('step-label').textContent=step<0?'Ready':`Step ${step+1} of ${solution.length}`;document.getElementById('current-move').textContent=step<0?'—':solution[step]||'—'}
function showSolution(){const box=document.getElementById('solution-card');box.classList.remove('hidden');document.getElementById('move-count').textContent=`${solution.length} move${solution.length===1?'':'s'}`;const m=document.getElementById('moves');m.innerHTML='';solution.forEach((x,i)=>{const b=document.createElement('button');b.className='move';b.textContent=x;b.onclick=()=>{stopPlayback();setStep(i)};m.appendChild(b)});build3D();setStep(-1)}
function ensureSolver(){if(!solverReady){Cube.initSolver();solverReady=true}}
function solve(){stopPlayback();const err=validate();const status=document.getElementById('status');if(err){status.textContent=err;return}if(typeof Cube==='undefined'){status.textContent='Solver library did not load.';return}status.textContent='Preparing solver…';try{ensureSolver();initialFacelets=facelets();const cube=Cube.fromString(initialFacelets);const result=cube.solve().trim();solution=result?result.split(/\s+/):[];step=-1;status.textContent=solution.length?'Solved! Use Play or tap a move.':'Cube is already solved.';showSolution()}catch(e){console.error(e);status.textContent='This cube configuration is invalid or unsolvable. Check the colors and try again.'}}
function example(){stopPlayback();state=solved();const moves="R U R' U R U2 R'";const c=Cube.fromString(facelets());c.move(moves);const s=c.asString();let k=0;faces.forEach(f=>{state[f]=s.slice(k,k+9).split('');k+=9});render();document.getElementById('status').textContent='Example scramble loaded. Tap Solve Cube.'}
function stopPlayback(){if(playTimer){clearInterval(playTimer);playTimer=null}const b=document.getElementById('play');if(b)b.textContent='▶ Play'}
function togglePlayback(){if(!solution.length)return;if(playTimer){stopPlayback();return}if(step>=solution.length-1)setStep(-1);document.getElementById('play').textContent='⏸ Pause';playTimer=setInterval(()=>{if(step<solution.length-1)setStep(step+1);else stopPlayback()},Number(document.getElementById('speed').value))}

document.getElementById('reset').onclick=reset;document.getElementById('solve').onclick=solve;document.getElementById('scramble').onclick=example;document.getElementById('prev').onclick=()=>{stopPlayback();setStep(step-1)};document.getElementById('next').onclick=()=>{stopPlayback();setStep(step+1)};document.getElementById('play').onclick=togglePlayback;document.getElementById('speed').onchange=()=>{if(playTimer){stopPlayback();togglePlayback()}};document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(solution.join(' '));document.getElementById('status').textContent='Solution copied.'}catch{document.getElementById('status').textContent='Copy failed.'}};

const cube3d=document.getElementById('cube3d');let dragging=false,lastX=0,lastY=0;cube3d.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;cube3d.setPointerCapture(e.pointerId)});cube3d.addEventListener('pointermove',e=>{if(!dragging)return;rotY+=(e.clientX-lastX)*0.5;rotX-=(e.clientY-lastY)*0.5;rotX=Math.max(-80,Math.min(80,rotX));lastX=e.clientX;lastY=e.clientY;cube3d.style.transform=`rotateX(${rotX}deg) rotateY(${rotY}deg)`});cube3d.addEventListener('pointerup',()=>dragging=false);cube3d.addEventListener('pointercancel',()=>dragging=false);

reset();