const faces=['U','R','F','D','L','B'];
const colors={U:'#f8f8f8',R:'#e53935',F:'#39b54a',D:'#ffd92f',L:'#ff8c2f',B:'#3385ff'};
window.rubiksColors=colors;
let state={};let selected='U';let solution=[];let step=-1;let solverReady=false;
function solved(){const s={};faces.forEach(f=>s[f]=Array(9).fill(f));return s}
function render(){const net=document.getElementById('cube-net');net.innerHTML='';[['U',1,0],['L',0,1],['F',1,1],['R',2,1],['B',3,1],['D',1,2]].forEach(([f,col,row])=>{const el=document.createElement('div');el.className='face';el.style.gridColumn=col+1;el.style.gridRow=row+1;el.innerHTML=`<div class="face-title">${f==='F'?'FRONT':f==='U'?'UP':f==='D'?'DOWN':f==='L'?'LEFT':f==='R'?'RIGHT':'BACK'}</div><div class="stickers"></div>`;const grid=el.querySelector('.stickers');state[f].forEach((v,i)=>{const b=document.createElement('button');b.className='sticker';b.style.background=colors[v];b.title=`${f}${i+1}`;b.onclick=()=>{state[f][i]=selected;render()};grid.appendChild(b)});net.appendChild(el)});const counter=document.createElement('div');counter.className='color-counter';counter.id='color-counter';counter.setAttribute('aria-label','Color counts');counter.innerHTML='<div class="counter-grid"></div>';counter.querySelector('.counter-grid').innerHTML=faces.map(f=>`<div class="count-item"><span class="count-swatch" style="background:${colors[f]}"></span><span class="count-number">0</span></div>`).join('');net.appendChild(counter);renderColorCounter();window.rubiksViewerState=state;renderPalette()}
function renderColorCounter(){const counter=document.getElementById('color-counter');if(!counter)return;const counts=Object.fromEntries(faces.map(f=>[f,0]));faces.forEach(f=>state[f].forEach(c=>{if(c in counts)counts[c]++}));counter.querySelectorAll('.count-item').forEach((item,i)=>{const n=counts[faces[i]];const num=item.querySelector('.count-number');num.textContent=n;item.classList.toggle('complete',n===9);item.classList.toggle('over',n>9)});counter.title=`${Object.values(counts).reduce((a,b)=>a+b,0)}/54 stickers`}
function renderPalette(){const p=document.getElementById('palette');p.innerHTML='';faces.forEach(f=>{const b=document.createElement('button');b.className='color-btn'+(selected===f?' selected':'');b.style.background=colors[f];b.title=f;b.onclick=()=>{selected=f;renderPalette()};p.appendChild(b)})}
function reset(){state=solved();selected='U';solution=[];step=-1;document.getElementById('solution-card').classList.add('hidden');document.getElementById('status').textContent='';render()}
function facelets(){return faces.map(f=>state[f].join('')).join('')}
function validate(){const counts=Object.fromEntries(faces.map(f=>[f,0]));for(const f of faces)for(const c of state[f]){if(!(c in counts))return 'Invalid color';counts[c]++}for(const f of faces)if(counts[f]!==9)return `You need exactly 9 ${f} stickers.`;const centers=faces.map(f=>state[f][4]);if(new Set(centers).size!==6)return 'Each center tile must have a different color.';return null}
function normalizedFacelets(){const byCenter={};faces.forEach(f=>{byCenter[state[f][4]]=f});return faces.map(f=>state[f].map(c=>byCenter[c]).join('')).join('')}
function showSolution(){const box=document.getElementById('solution-card');box.classList.remove('hidden');document.getElementById('move-count').textContent=`${solution.length} move${solution.length===1?'':'s'}`;const m=document.getElementById('moves');m.innerHTML='';solution.forEach((x,i)=>{const b=document.createElement('button');b.className='move'+(i===step?' active':'');b.textContent=x;b.onclick=()=>{step=i;updateStep()};m.appendChild(b)});updateStep()}
function updateStep(){document.querySelectorAll('.move').forEach((b,i)=>b.classList.toggle('active',i===step));document.getElementById('step-label').textContent=step<0?'Ready':`Step ${step+1} of ${solution.length}`;document.getElementById('current-move').textContent=step<0?'—':solution[step]}
function ensureSolver(){if(!solverReady){Cube.initSolver();solverReady=true}}
function solve(){const err=validate();const status=document.getElementById('status');if(err){status.textContent=err;return}if(typeof Cube==='undefined'){status.textContent='Solver library did not load.';return}status.textContent='Preparing solver…';try{ensureSolver();const cube=Cube.fromString(normalizedFacelets());const result=cube.solve().trim();solution=result?result.split(/\s+/):[];step=-1;status.textContent=solution.length?'Solved! Follow the moves below.':'Cube is already solved.';showSolution()}catch(e){console.error(e);status.textContent='This cube configuration is invalid or unsolvable. Check the colors and try again.'}}
function example(){state=solved();const moves="R U R' U R U2 R'";const c=Cube.fromString(facelets());c.move(moves);const s=c.asString();let k=0;faces.forEach(f=>{state[f]=s.slice(k,k+9).split('');k+=9});render();document.getElementById('status').textContent='Example scramble loaded. Tap Solve Cube.'}
function applyScannedFace(face,vals){state[face]=vals.slice();render()}
window.applyScannedFace=applyScannedFace;
document.getElementById('reset').onclick=reset;document.getElementById('solve').onclick=solve;document.getElementById('scramble').onclick=example;document.getElementById('prev').onclick=()=>{if(step>=0){step--;updateStep()}};document.getElementById('next').onclick=()=>{if(step<solution.length-1){step++;updateStep()}};document.getElementById('copy').onclick=async()=>{try{await navigator.clipboard.writeText(solution.join(' '));document.getElementById('status').textContent='Solution copied.'}catch{document.getElementById('status').textContent='Copy failed.'}};reset();